# Generated by Django 5.0.4 on 2024-04-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Transisting', 'Transisting')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Pending', 'Pending')], default='Pending', max_length=30),
        ),
    ]
