# Generated by Django 5.0.4 on 2024-04-11 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_order_delivery_status_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.order'),
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
